[package]
name = "dbbackend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = "0.9.1"
dotenv = "0.15.0"
tokio-test="0.4.1"

migration = {path="../migration"}
entity = {path="../entity"}